sudo: required
services:
  - docker

before_install:
# can use any tag name.
  - docker build -t sasimandava/docker-react -f Dockerfile.dev .

  script:
    - docker run sasimandava/docker-react npm run test -- --coverage
  
  deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker_test"
    env: "Dockertest-env"
    bucker_name: "elasticbeanstalk-us-west-2-250618505106"
    bucket_path: "docker_test" #Use the same as app name as the folder name gets created only after deploy.
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"


