sudo: required
services:
  - docker

before_install:
# can use any tag name.
  - docker build -t sasimandava/docker-react -f Dockerfile.dev .

  script:
    - docker run sasimandava/docker-react npm run test -- --coverage
